src/HIP/WaveSlidesBundle/Controller/AbstractController.php
<?php
/**
 * @author Stefan Beier
 */

namespace HIP\WaveSlidesBundle\Controller;

use Doctrine\ODM\MongoDB\DocumentManager;
use HIP\WaveSlidesCoreBundle\Document\Account\WaveUser;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\Request;

class AbstractController extends Controller {

    /**
     * Post field name containing json data.
     */
    const AJAX = 'json';

    /**
     * @var array
     */
    private $ajaxData;

    /**
     * @return DocumentManager
     */
    public function dm() {
        return $this->get('doctrine_mongodb')->getManager();
    }

    /**
     * For better IDE typechecking
     * @return WaveUser
     */
    public function getUser() {
        return parent::getUser();
    }

    /**
     * Ajax data is stored in the "ajax" parameter of the post data
     * Returns the complete ajax data as key value array
     * @param string $key
     * @return mixed
     * @throws Exception
     */
    protected function getAjax($key) {
        if ($this->ajaxData == null)
            throw new Exception('Ajax data not initialized. Did you forgot to call initAjax(Request)');
        return $this->ajaxData[$key];
    }

    protected function initAjax(Request $request) {
        $this->ajaxData = json_decode($request->request->get(self::AJAX), true);
    }

}

src/HIP/WaveSlidesBundle/Controller/EditorController.php
<?php
/**
 * @author Stefan Beier
 */

namespace HIP\WaveSlidesBundle\Controller;

use HIP\WaveSlidesCoreBundle\Common\ServiceHelper;
use HIP\WaveSlidesCoreBundle\Document\Deck;
use HIP\WaveSlidesCoreBundle\Document\System;
use Sensio\Bundle\FrameworkExtraBundle\Configuration as Sensio;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @Sensio\Route("/editor")
 * @Sensio\Security("has_role('ROLE_USER')")
 */
class EditorController extends AbstractController {

    /**
     * Starts the WaveEditor App.
     * @Sensio\Route("/{id}", name="editor_index", options={"expose"=true})
     * @Sensio\Method("GET")
     * @Sensio\Template()
     * @param string $id
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function indexAction($id) {
        /** @var Deck $deck */
        $deck = $this->getUser()->getDeck($id);

        if ($deck == null)
            return new RedirectResponse($this->generateUrl('dashboard_index'));

        return array(
            'deck_id' => $deck->getId(),
            'ws_ip' => $this->wsIP(),
            'languages' => $this->dm()->getRepository('HIPWaveSlidesCoreBundle:SlideElements\ScriptLanguage')->findAll(),
            'strings' => System::instance()->getStrings()
        );

    }

    private function wsIP() {
        return ServiceHelper::parameter('ws_ip') . ':' . ServiceHelper::parameter('ws_port');
    }

} 

src/HIP/WaveSlidesBundle/Resources/views/Editor/chat.html.twig
<div style="display: none;" class="chatContainer minimized">

    <div class="chatTitleBar">
        <p>Chat <span id="unreadMessageCount"></span></p>

        <div class="muteButton"></div>
        <div class="minimizeIndicator"></div>
    </div>

    <div class="chatBox">
        <div id="sound"></div>
        <div class="conversations"></div>
        <div class="chatInput"><input type="text" placeholder="{{ strings.write_something }}"/></div>
    </div>

</div>

src/HIP/WaveSlidesBundle/Resources/views/Editor/colorpicker_rgb.html.twig
<div style="display: none" class="ui-color-slider {% block class %}rgb{% endblock %}">
    <div class="red row">
        <div class="background"></div>
        <canvas width="160" height="10"></canvas>
        <div class="slider"></div>
        <input value="0" type="text"/>
    </div>
    <div class="green row">
        <div class="background"></div>
        <canvas width="160" height="10"></canvas>
        <div class="slider"></div>
        <input value="0" type="text"/>
    </div>
    <div class="blue row">
        <div class="background"></div>
        <canvas width="160" height="10"></canvas>
        <div class="slider"></div>
        <input value="0" type="text"/>
    </div>
    {% block alpha %}{% endblock %}
</div>

src/HIP/WaveSlidesBundle/Resources/views/Editor/colorpicker_rgba.html.twig
{% extends 'HIPWaveSlidesBundle:Editor:colorpicker_rgb.html.twig' %}

{% block class %}rgba{% endblock %}

{% block alpha %}
    <div class="alpha row">
        <div class="background"></div>
        <canvas width="160" height="10"></canvas>
        <div class="slider"></div>
        <input value="0" type="text"/>
    </div>
{% endblock %}

src/HIP/WaveSlidesBundle/Resources/views/Editor/index.html.twig
{% extends "HIPWaveSlidesBundle::base.html.twig" %}

{% block html_style %}background-color: white;{% endblock %}

{% block title %}WaveSlides Editor{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/hipwaveslides/css/lib/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/hipwaveslides/css/lib/jquery.mCustomScrollbar.css') }}"/>
    <link rel="stylesheet" href="{{ asset('bundles/hipwaveslides/css/lib/spectrum.css') }}"/>
    <link rel="stylesheet/less" href="{{ asset('bundles/hipwaveslides/css/editor.less') }}"/>
    <link rel="stylesheet" href="{{ asset('bundles/hipwaveslides/css/lib/highlightjs/styles/default.css') }}">
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>

    <script type="text/javascript" src="{{ asset('bundles/hipwaveslides/js/build/out/editor.lib.build.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/hipwaveslides/js/EditorConfig.js') }}"></script>
    <script type="text/javascript">
        var DECK_ID = "{{ deck_id }}";
        var SESSION_ID = "{{ app.user.session.id }}";
        var USER_ID = "{{ app.user.id  }}";
        var WS_URL = "{{ ws_ip }}";
        var CON_ID = "";
    </script>
{% endblock %}

{% block body_style %}background-color: white;{% endblock %}

{% block body %}
    <div style="margin-left: auto; margin-right: auto; margin-top: 50px; width: 215px;" class="waveloader"><img src="{{ asset('bundles/hipwaveslides/images/waveloader.gif') }}"/></div>

    <div style="display: none;" class="waveeditor">

        {{ include('HIPWaveSlidesBundle:Editor:toolbar.html.twig') }}

        <div class="ui-main-view" style="position: relative">

            <div style="min-height: 100%; position: absolute;" class="uiSlideSidebar"></div>

            <div class="main">

                <div class="uiSlideContainer">

                    <div class="flash-container">
                        <div class="message"></div>
                    </div>

                    <div class="uploads" style="display: none">
                        <div style="display: none" class="clone upload">
                            <div class="info">
                                <span class="filename"></span>, <span class="uploadedsize">0</span> kb / <span class="totalsize">0</span> kb
                            </div>
                            <div class="barwrapper"><span style="width: 0%;" class="bar"></span></div>
                        </div>
                    </div>

                    <div style="display: none" class="uiDropoverlay">
                        <div class="inner">
                            <p style="display: none;" class="dragInfo">{{ strings.drag_images_here }}</p>
                            <p style="display: none;" class="dropInfo">{{ strings.place_images_here }}</p>
                        </div>
                    </div>

                </div>

                <div class="connectedUsersPanel">
                    <div class="users"></div>
                </div>

            </div>

            {{ include ('HIPWaveSlidesBundle:Editor:properties.html.twig') }}

            <div class="clear"></div>

        </div>

    </div>

    <div style="display: none" class="resizeTooltip"></div>

    {{ include ('HIPWaveSlidesBundle:Editor:colorpicker_rgb.html.twig') }}

    {{ include ('HIPWaveSlidesBundle:Editor:colorpicker_rgba.html.twig') }}

    {{ include ('HIPWaveSlidesBundle:Editor:chat.html.twig') }}

{% endblock %}

src/HIP/WaveSlidesBundle/Resources/views/Editor/properties.html.twig
<div class="left properties">

    <div style="display: none" class="window element">

        <div class="panel title">
            <div class="elementIcon left icon"></div>
            <span class="name left"></span>

            <div class="clear"></div>
        </div>

        <div style="display: none" class="panel imageView">
            <p class="title">{{ strings.info }}:</p>

            <div>{{ strings.original_width }}: <span class="originalWidth"></span>px</div>
            <div>{{ strings.original_height }}: <span class="originalHeight"></span>px</div>
        </div>

        <div style="display: none" class="panel scriptView">
            <p class="title">{{ strings.language }}:</p>

            <select class="language" name="language">
                {% for language in languages %}
                    <option data-css="{{ language.css }}" value="{{ language.value }}">{{ language.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="panel appearance">
            <p class="title">{{ strings.appearance }}</p>

            <div class="option alpha">

                <div class="left" style="margin-right: 16px;">{{ strings.opacity }}: <span class="alpha"></span></div>
                <input value="0" class="ui-number-spinner propertyAlphaSpinner"/>

                <div class="clear"></div>
            </div>
            <div class="option background">
                <div class="left" style="margin-right: 16px;">{{ strings.background_color }}: <span class="alpha"></span></div>
                <div class="left ui-color-field">
                    <div class="color"></div>
                    <div class="placeholder"></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>

        <div class="panel bounds">
            <p class="title">{{ strings.bounds }}:</p>

            <div class="option">
                <div class="left label">{{ strings.width }}:</div>
                <input value="0" class="ui-number-spinner propertyWidthSpinner"/>

                <div style="width: 15px;" class="left label">X:</div>
                <input value="0" class="ui-number-spinner propertyXSpinner"/>

                <div class="clear"></div>
            </div>

            <div class="option">
                <div class="left label">{{ strings.height }}:</div>
                <input value="0" class="ui-number-spinner propertyHeightSpinner"/>

                <div style="width: 15px;" class="left label">Y:</div>
                <input value="0" class="ui-number-spinner propertyYSpinner"/>

                <div class="clear"></div>
            </div>
        </div>

    </div>

    <div class="window slide">
        <div class="title">
            <div class="left icon slide"></div>
            <span class="left">{{ strings.slide }}</span>

            <div class="clear"></div>
        </div>

        <div class="option">
            <div class="left label">{{ strings.background_color }}:</div>
            <div class="left ui-color-field">
                <div class="color"></div>
                <div class="placeholder"></div>
            </div>
            <div class="clear"></div>
        </div>

    </div>

    <div class="window deck">
        <div class="title">
            <div class="left icon settings"></div>
            <span class="left">{{ strings.deck }}</span>

            <div class="clear"></div>
        </div>
    </div>

</div>

src/HIP/WaveSlidesBundle/Resources/views/Editor/toolbar.html.twig
<div class="ui-toolbar">

    <div class="top">

        <div class="ui-button" id="newSlide">
            <div class="icon"></div>
            <span>{{ strings.new }}</span>
        </div>

        <div class="ui-button" id="play">
            <a target="_blank" href="{{ path('player_index', {id: deck_id}) }}">
                <div class="icon"></div>
                <span>{{ strings.play }}</span>
            </a>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button" id="newTextView">
            <div class="icon"></div>
            <span>{{ strings.textfield }}</span>
        </div>

        <div class="ui-button" id="newCode">
            <div class="icon"></div>
            <span>{{ strings.code }}</span>
        </div>

        <div class="ui-button ui-state-disabled" id="newShape">
            <div class="icon"></div>
            <span>{{ strings.shape }}</span>
        </div>

        <div class="ui-button" id="newImage">
            <div class="icon"></div>
            <span>{{ strings.image }}</span>
        </div>
        <input id="fileChooser" style="display: none" multiple type="file"/>

        <div class="ui-button" id="newTable">
            <div class="icon"></div>
            <span>{{ strings.table }}</span>
        </div>

        <div class="ui-button ui-state-disabled" id="newChart">
            <div class="icon"></div>
            <span>{{ strings.chart }}</span>
        </div>

        <div class="ui-button ui-state-disabled" id="newFormula">
            <div class="icon"></div>
            <span>{{ strings.formula }}</span>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button ui-state-disabled" id="pushToFront">
            <div class="icon"></div>
            <span>{{ strings.step_forward }}</span>
        </div>

        <div class="ui-button ui-state-disabled" id="pushToBack">
            <div class="icon"></div>
            <span>{{ strings.step_backward }}</span>
        </div>

        <div class="clear"></div>

    </div>

    <div class="clear"></div>

    <div class="bottom">

        <div class="ui-button-group fontFormatButton">
            <input style="display: none;" id="textFontSize" value="10"/>
        </div>

        <div class="ui-button-group textFormatButton">
            <button class="ui-button ui-state-disabled" id="textFormatBold" data-format="bold"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textFormatItalic" data-format="italic"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textFormatUnderline" data-format="underline"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textFormatStrikeout" data-format="strikeThrough"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textFormatSuper" data-format="superscript"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textFormatSub" data-format="subscript"><span></span></button>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button-group textAlignButton">
            <button class="ui-button ui-state-disabled" id="textAlignLeft" data-format="justifyLeft"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textAlignCenter" data-format="justifyCenter"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textAlignRight" data-format="justifyRight"><span></span></button>
            <button class="ui-button ui-state-disabled" id="textAlignJustify" data-format="justifyFull"><span></span></button>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button-group objectAlignButton">
            <button class="ui-button ui-state-disabled" id="alignLeft"><span></span></button>
            <button class="ui-button ui-state-disabled" id="alignHorizontalCenter"><span></span></button>
            <button class="ui-button ui-state-disabled" id="alignRight"><span></span></button>
            <button class="ui-button ui-state-disabled" id="alignTop"><span></span></button>
            <button class="ui-button ui-state-disabled" id="alignVerticalCenter"><span></span></button>
            <button class="ui-button ui-state-disabled" id="alignBottom"><span></span></button>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button-group objectDistributeButton">
            <button class="ui-button ui-state-disabled" id="distributeLeft"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeHorizontalCenter"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeRight"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeTop"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeVerticalCenter"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeBottom"><span></span></button>
        </div>

        <div class="ui-separator"></div>

        <div class="ui-button-group objectDistributeButton">
            <button class="ui-button ui-state-disabled" id="distributeHorizontalEqual"><span></span></button>
            <button class="ui-button ui-state-disabled" id="distributeVerticalEqual"><span></span></button>
        </div>

        <div class="ui-separator"></div>

        <div class="clear"></div>

    </div>

</div>